
services:
  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    networks:
      - backend_net
    
  client-api:
    build:
      context: .
      dockerfile: ClientAPI/Dockerfile
    networks:
      - client_net
      - backend_net
    ports:
      - 9411:80

networks:
  backend_net:
    external: false
  
  client_net:
    external: true